name: build-nightly

on:
  push:
    branches:
      - dev
    paths:
      - "update/**"

jobs:
  build:
    runs-on: debian-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to Docker Registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_URL }}

      - name: Build & push daemon image
        run: |
          docker build -f ./docker/updater.Dockerfile -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/dm-updater:latest . --push

      - name: Clean docker image
        run: |
          docker rmi ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/dm-updater:latest