services:
  daemon:
    image: git.mczhengyi.top/zhengyi/dm-daemon:nightly
    container_name: dm-daemon
    restart: always
    environment:
      - BASE_PATH=/Users/liuzhengyi/docker-mng
      - ENABLE_TRAEFIK=true
    volumes:
      - /Users/liuzhengyi/docker-mng:/Users/liuzhengyi/docker-mng
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001

x-dm:
  protected: true